#!/usr/bin/env python3
"""
base_installer.py – установщик компилятора GCC для Ely.
Лицензия GCC выводится пользователю, ответственность за соблюдение условий лежит на нём.
"""

import os
import sys
import platform
import shutil
import subprocess
import tempfile
import urllib.request
import json
from pathlib import Path

class CompilerInstaller:
    def __init__(self, project_root=None):
        if project_root is None:
            # When frozen by PyInstaller, __file__ points to temp directory.
            # sys.executable gives the actual .exe location.
            if getattr(sys, 'frozen', False):
                project_root = Path(sys.executable).parent
            else:
                project_root = Path(__file__).parent.parent
        self.project_root = Path(project_root)
        self.tools_dir = self.project_root / 'tools'
        self.gcc_dir = self.tools_dir / 'gcc'
        self.config_file = self.project_root / '.ely_config'

    def _show_license(self):
        license_text = """
The source code is distributed under the GNU General Public License version 3, with the addition under section 7 of an exception described in the “GCC Runtime Library Exception, version 3.1” as follows (or see the file COPYING.RUNTIME):

GCC RUNTIME LIBRARY EXCEPTION

Version 3.1, 31 March 2009

Copyright (C) 2009 Free Software Foundation, Inc.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

This GCC Runtime Library Exception ("Exception") is an additional
permission under section 7 of the GNU General Public License, version
3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
bears a notice placed by the copyright holder of the file stating that
the file is governed by GPLv3 along with this Exception.

When you use GCC to compile a program, GCC may combine portions of
certain GCC header files and runtime libraries with the compiled
program. The purpose of this Exception is to allow compilation of
non-GPL (including proprietary) programs to use, in this way, the
header files and runtime libraries covered by this Exception.

0. Definitions.

A file is an "Independent Module" if it either requires the Runtime
Library for execution after a Compilation Process, or makes use of an
interface provided by the Runtime Library, but is not otherwise based
on the Runtime Library.

"GCC" means a version of the GNU Compiler Collection, with or without
modifications, governed by version 3 (or a specified later version) of
the GNU General Public License (GPL) with the option of using any
subsequent versions published by the FSF.

"GPL-compatible Software" is software whose conditions of propagation,
modification and use would permit combination with GCC in accord with
the license of GCC.

"Target Code" refers to output from any compiler for a real or virtual
target processor architecture, in executable form or suitable for
input to an assembler, loader, linker and/or execution
phase. Notwithstanding that, Target Code does not include data in any
format that is used as a compiler intermediate representation, or used
for producing a compiler intermediate representation.

The "Compilation Process" transforms code entirely represented in
non-intermediate languages designed for human-written code, and/or in
Java Virtual Machine byte code, into Target Code. Thus, for example,
use of source code generators and preprocessors need not be considered
part of the Compilation Process, since the Compilation Process can be
understood as starting with the output of the generators or
preprocessors.

A Compilation Process is "Eligible" if it is done using GCC, alone or
with other GPL-compatible software, or if it is done without using any
work based on GCC. For example, using non-GPL-compatible Software to
optimize any GCC intermediate representations would not qualify as an
Eligible Compilation Process.

1. Grant of Additional Permission.

You have permission to propagate a work of Target Code formed by
combining the Runtime Library with Independent Modules, even if such
propagation would otherwise violate the terms of GPLv3, provided that
all Target Code was generated by Eligible Compilation Processes. You
may then convey such a combination under terms of your choice,
consistent with the licensing of the Independent Modules.

2. No Weakening of GCC Copyleft.

The availability of this Exception does not imply any general
presumption that third-party software is unaffected by the copyleft
requirements of the license of GCC.
    

Hopefully that text is self-explanatory. If it isn't, you need to speak to your lawyer, or the Free Software Foundation.
"""
        print(license_text)
        response = input("Do you accept the license? (yes/no): ").strip().lower()
        if response != 'yes':
            print("Installation aborted.")
            return False
        return True

    def install(self, version=None):
        if not self._show_license():
            return 1

        if sys.platform == 'win32':
            return self._install_windows(version)
        elif sys.platform.startswith('linux'):
            return self._install_linux(version)
        elif sys.platform == 'darwin':
            return self._install_macos(version)
        else:
            print(f"Unsupported platform: {sys.platform}")
            return 1

    def _install_windows(self, version):
        # Используем предсобранные MinGW-w64 от winlibs.com
        # URL для версии по умолчанию (можно расширить выбор версий)
        url = "https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0-16.0.6-11.0.1-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r1.7z"
        print(f"Downloading GCC from {url}...")

        self.tools_dir.mkdir(exist_ok=True)
        archive_path = self.tools_dir / "gcc.7z"

        try:
            urllib.request.urlretrieve(url, archive_path)
        except Exception as e:
            print(f"Download failed: {e}")
            return 1

        # Проверяем наличие 7z
        seven_zip = shutil.which('7z')
        if not seven_zip:
            print("7-Zip not found in PATH. Please install 7-Zip or add it to PATH.")
            return 1

        # Удаляем старую установку, если есть
        if self.gcc_dir.exists():
            shutil.rmtree(self.gcc_dir)
        self.gcc_dir.mkdir(parents=True)

        print("Extracting archive...")
        subprocess.run([seven_zip, 'x', str(archive_path), f'-o{self.gcc_dir}'], check=True)
        archive_path.unlink()  # удаляем архив

        # Ожидаемая структура: внутри архива папка mingw64, перемещаем всё на уровень выше
        extracted_root = self.gcc_dir / 'mingw64'
        if extracted_root.exists():
            for item in extracted_root.iterdir():
                shutil.move(str(item), str(self.gcc_dir))
            extracted_root.rmdir()

        print(f"GCC installed successfully to {self.gcc_dir}")
        return 0

    def _install_linux(self, version):
        print("On Linux it is recommended to install GCC using your package manager.")
        print("Example: sudo apt install gcc    (Debian/Ubuntu)")
        print("         sudo dnf install gcc    (Fedora)")
        print("         sudo pacman -S gcc      (Arch)")
        resp = input("Do you want to proceed with manual download? (not recommended) [y/N]: ")
        if resp.lower() != 'y':
            return 0
        # Для простоты можно также загружать с официального сайта GCC, но это сложно.
        # Вместо этого просто проверяем наличие gcc в системе.
        if shutil.which('gcc'):
            print("GCC is already available in PATH.")
        else:
            print("GCC not found. Please install it via your package manager.")
        return 0

    def _install_macos(self, version):
        print("On macOS, please install GCC via Homebrew: brew install gcc")
        return 0

    def remove(self):
        if self.gcc_dir.exists():
            shutil.rmtree(self.gcc_dir)
            print("GCC removed from tools/")
        else:
            print("No GCC installation found in tools/")
        return 0

    def list_versions(self):
        print("Available GCC versions for Windows (winlibs):")
        print(" - 13.2.0 (default)")
        # Можно добавить парсинг страницы релизов GitHub
        return 0

    def set_custom_path(self, path_str):
        path = Path(path_str).resolve()
        if not path.exists() or not path.is_file():
            print(f"Error: '{path}' does not exist or is not a file.")
            return 1

        config = {}
        if self.config_file.exists():
            with open(self.config_file, 'r') as f:
                config = json.load(f)
        config['compiler_path'] = str(path)
        with open(self.config_file, 'w') as f:
            json.dump(config, f, indent=4)
        print(f"Custom compiler path set to {path}")
        return 0